"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory$git_branch$rust$python: """

[character]

format = "$symbol"

[directory]
style = 'bold italic fg:green'

[git_branch]
format = 'on [$symbol$branch(:$remote_branch)]($style) '

[rust]
symbol = ' '
[python]
symbol = '[ ](fg:cyan bold)'
style = 'bold fg:yellow'
format = '[via ](fg:white bold)[$symbol${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
